export const CHANGE_ISVERIFIED_STATE = 'CHANGE_ISVERIFIED_STATE';
export const CHANGE_ISADMIN_STATE = 'CHANGE_ISADMIN_STATE';
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PHONE = 'SET_PHONE';
